# Generated by Django 4.1.7 on 2023-06-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=111)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="media")),
                (
                    "description",
                    models.CharField(
                        default="No description available", max_length=500
                    ),
                ),
            ],
        ),
    ]
