# Generated by Django 4.1.7 on 2023-06-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_cartitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="item",
            new_name="name",
        ),
    ]
